<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\target\debug\clipboard_ffi.dll"
          Link="clipboard_ffi.dll"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
